### PR TITLE
view events

### PR DESCRIPTION
**Pull request by mmccart40**
# Story

_As a user I want to be able to view an event._

Acceptance Criteria
==============
1. View all events displays the events
2. Clicking on the event from that page takes you directly to viewing that event
3. You can see all the event info with no issues
4. You are able to view multiple events

### CODE REVIEW

**Review by avadonley — COMMENTED** [review]
Madi, the code looks very neat.

**Comment by mmccart40** [comment]
> Madi, the code looks very neat.

Thank you very much!

**Comment by avadonley** [comment]
> > Madi, the code looks very neat.
> 
> Thank you very much!

You're welcome!

**Comment by avadonley** [comment]
> > > Madi, the code looks very neat.
> > 
> > 
> > Thank you very much!
> 
> You're welcome!

There seems to be some merging conflicts, but I understand this is being handled by Thomas.

**Comment by avadonley** [comment]
> > > > Madi, the code looks very neat.
> > > 
> > > 
> > > Thank you very much!
> > 
> > 
> > You're welcome!
> 
> There seems to be some merging conflicts, but I understand this is being handled by Thomas.

Hi, Madi! I noticed a few opportunities for improvement in your code. I noticed that you added comments which was fantastic! In future you should comment more frequently, especially on lengthy or complex functionality, such as new functions (e.g. showDeleteConfirmation).
I think it would also be helpful to mention why you are referencing certain documents in the files you edit. For example, in viewAllEvents.php, you include 'database/dbEvents.php'. You can add a comment explaining why this file was included (what functionality within it is used).

**Pull request closed without merging**
